# About this book {.unnumbered}

## How this book is organised {.unnumbered}

> TODO: Explain the chapters in this book.

## Prerequisites {.unnumbered}

The beginning chapters are suitable for data and statistics producers with no prior knowledge of linked data, but with some basic knowledge of R or Python. For readers without programming experience, we recommend ["R for Data Science"](https://r4ds.had.co.nz/) by Hadley Wickham and Garrett Grolemund as an introduction to the R statistical programming language. 

Later chapters explain our data architecture, use of open standards, and the issues and debates we've had along the way. Those already familiar with linked data and the semantic web may wish to skip ahead.

## Colophon {.unnumbered}

This book was written in [RStudio](http://www.rstudio.com/ide/) using [bookdown](http://bookdown.org/).
The complete source is available from [GitHub](https://github.com/GSS-Cogs/linked-data-book).

This version of the book was built with `r R.version.string` and the following packages:

```{r, echo = FALSE, results="asis"}
deps <- desc::desc_get_deps()
pkgs <- sort(deps$package[deps$type == "Imports"])
pkgs <- sessioninfo::package_info(pkgs, dependencies = FALSE)
df <- tibble::tibble(
  package = pkgs$package,
  version = pkgs$ondiskversion,
  source = gsub("@", "\\\\@", pkgs$source)
)
knitr::kable(df, format = "markdown")
```